### ISSUE TITLE
How to use Manta output for ShatterSeek? No Strand info, and different SVtype

### ISSUE THREAD

**Issue by arianlundberg** [parklab/ShatterSeek#30]
Hi,

I'd like to use the output from Manta as an input for SVs function, however, I don't have the strand info in the Manta calls, is it ok to put + instead for both strands? and which of the manta SVtypes are supported here (BND, DEL, DUP, INS, INV)? and if not supported, what do I need to do with those calls, perhaps changing them to TRA?

Thanks for this great tool and support.

**Comment by isidroc** [comment]
Hello, you could use e.g. mergevcf to obtain a ShatterSeek compatible notation. 
Best,
Isidro

**Comment by arianlundberg** [comment]
Thanks, I understood that from the discussion in the issue section. but my second question was about the outputs from Manta, which are VCFs, so, what do I need to do we the SV-types from it and what is supported with ShatterSeek? I assume MergeVCF doesn't change anything from the VCF outputs from Manta, right? Do I need to use another tool for SV calls? if so, what would be your recommendation? Thanks

**Comment by isidroc** [comment]
Hello, I would suggest that you try to use mergevcf as indicated above (please read the documentation rather than assuming what it does) and/or convert the manta calls to the notation used in PCAWG (+/- for deletions; -/+ for duplications, etc). If you have questions about the output of manta it would be better for you to contact the developers of that tool. Hope this helps, Isidro
